[project]
name = "snapy"
version = "2.0.0"
description = "Python Testing Framework with Argument Capture and Function Tracing"
authors = [
    {name = "Matevž Vidovič",email = "matevz.vidovic@gmail.si"}
]
requires-python = ">=3.11"
dependencies = [
    "syrupy (>=4.9.1,<5.0.0)",
    "pytest (>=8.4.2,<9.0.0)",
    "dill (>=0.3.6,<1.0.0)"
]

[project.optional-dependencies]
enhanced_serialization = ["dill (>=0.3.6,<1.0.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
