[tool.poetry]
name = "snapy"
version = "0.1.0"
description = ""
authors = ["Matevž Vidovič <matevz.vidovic@gmail.si>"]
readme = "README.md"

[tool.pytest.ini_options]
pythonpath = ["src", "."]

[tool.poetry.dependencies]
python = "^3.11"
syrupy = "^5.0.0"
pytest-mock = "^3.15.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
