from typing import Protocol, runtime_checkable


@runtime_checkable
class BasicOps(Protocol):
    def plus(self, a, b, c=..., d=...): ...
    def concatenation(self, a, b) -> str: ...
    def expression(self, a, b): ...
